import { Hind_Vadodara } from 'next/font/google'
import './globals.css'

const hind_vadodara = Hind_Vadodara({ subsets: ['latin'], weight: '400' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <title>Dream Agency</title>
      <body className={hind_vadodara.className}>{children}</body>
    </html>
  )
}
